### ISSUE TITLE
CONTRIBUTING.md would be great.

### ISSUE THREAD

**Issue by MySolace** [iambumblehead/gani#3]
While not explicitly necessary for a project to function, it would be considerably more simple and straightforward to include a CONTRIBUTING guide for people wishing to submit patches. The whole process of maintaining the project would be much simplified.

thanks!

**Comment by iambumblehead** [comment]
@MySolace thanks for your suggestion. Humbly, I did not anticipate any contributions here. The tests and examples are incomplete and there is no documentation or marketing at this time. I'm surprised anyone is interested in this repo...

I did add a CONTRIBUTING guide.

**Comment by iambumblehead** [comment]
I'm closing this ticket, feel free to re-open if you need.

**Comment by MySolace** [comment]
I've learned recently that only an arrogant person expects interest in their own work. :)
